// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0mPUSEuhyFCKlsgm7OVKnO-M4yRgZwC0',
    appId: '1:575535903166:web:46e8ab09323e61a9abc9ef',
    messagingSenderId: '575535903166',
    projectId: 'campuslink-25c35',
    authDomain: 'campuslink-25c35.firebaseapp.com',
    storageBucket: 'campuslink-25c35.firebasestorage.app',
    measurementId: 'G-K8N0CNVWSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBOJPavU0vuCWNEO3WiWWRkb8Q5IatiU',
    appId: '1:575535903166:android:3e49e804221ed796abc9ef',
    messagingSenderId: '575535903166',
    projectId: 'campuslink-25c35',
    storageBucket: 'campuslink-25c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAeb7nDDdEn2uQonGKSyZTv_mYbuQUyg',
    appId: '1:575535903166:ios:3f26c03a80a7a0c6abc9ef',
    messagingSenderId: '575535903166',
    projectId: 'campuslink-25c35',
    storageBucket: 'campuslink-25c35.firebasestorage.app',
    androidClientId: '575535903166-onrp594ol8gb6lcuo8aurs026rktmd2m.apps.googleusercontent.com',
    iosClientId: '575535903166-0347kdrrmq42a2mpshkjivllbpmda998.apps.googleusercontent.com',
    iosBundleId: 'com.example.campussocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAeb7nDDdEn2uQonGKSyZTv_mYbuQUyg',
    appId: '1:575535903166:ios:3f26c03a80a7a0c6abc9ef',
    messagingSenderId: '575535903166',
    projectId: 'campuslink-25c35',
    storageBucket: 'campuslink-25c35.firebasestorage.app',
    androidClientId: '575535903166-onrp594ol8gb6lcuo8aurs026rktmd2m.apps.googleusercontent.com',
    iosClientId: '575535903166-0347kdrrmq42a2mpshkjivllbpmda998.apps.googleusercontent.com',
    iosBundleId: 'com.example.campussocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0mPUSEuhyFCKlsgm7OVKnO-M4yRgZwC0',
    appId: '1:575535903166:web:a277e7c41e04c2b1abc9ef',
    messagingSenderId: '575535903166',
    projectId: 'campuslink-25c35',
    authDomain: 'campuslink-25c35.firebaseapp.com',
    storageBucket: 'campuslink-25c35.firebasestorage.app',
    measurementId: 'G-QWBG07K67K',
  );
}
